RIVER_KM = 20 
BARGE_SETUP_MINUTES = 20 #min
FILE_INPUT_NAME = 'CodeVS/data/input/Tugboat Problem V5-Demo.xlsx'
BARGE_RELEASE_MINUTES = 30 #min
KOH_SI_CHANG_STATION_BASE_REFERENCE_ID = "ST_001"
APPOINTMENT_STATION_BASE_REFERENCE_ID = "ST_014"
BAR_STATION_BASE_REFERENCE_ID = "ST_005"
LOAD_TEMP = True
INPUT_FOLDER = 'data/input/'
RELAX_DAYS = 2
MAX_RELAX_DAYS = 30
MAX_CRANES=7

TRAVEL_FACTOR = {
    'SEA_TUGBOAT_BARGE_COLLECTION_MAX_SPEED': 10,
    'SEA_TUGBOAT_BARGE_COLLECTION_MIN_SPEED': 6,
    'RIVER_TUGBOAT_BARGE_COLLECTION_MAX_SPEED': 6,
    'RIVER_TUGBOAT_BARGE_COLLECTION_MIN_SPEED': 3,
    'RIVER_FACTOR': 0.5,
    'SEA_FACTOR': 1,
}
